//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Model.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushUps
    {
        public string Exercise { get; set; }
        public bool StepOne { get; set; }
        public bool StepTwo { get; set; }
        public bool StepThree { get; set; }
    }
}
